name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os-version: [ ubuntu-latest ]
        compiler: [ gcc-latest ]
        deps: ['enabled']
        platform: ['x64', 'x86'] 

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install packages
      run: |
           sudo apt update
           sudo apt install -y libpcap-dev

    - name: Make
      run: make
